/*
 * generated by Xtext 2.19.0
 */
package org.sabsa.dasl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.sabsa.dasl.parser.antlr.internal.InternalDaslParser;
import org.sabsa.dasl.services.DaslGrammarAccess;

public class DaslParser extends AbstractAntlrParser {

	@Inject
	private DaslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDaslParser createParser(XtextTokenStream stream) {
		return new InternalDaslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "SecurityModel";
	}

	public DaslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DaslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
