/*
 * generated by Xtext 2.12.0
 */
package org.sabsa.dasl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.sabsa.dasl.ide.contentassist.antlr.internal.InternalDaslParser;
import org.sabsa.dasl.services.DaslGrammarAccess;

public class DaslParser extends AbstractContentAssistParser {

	@Inject
	private DaslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalDaslParser createParser() {
		InternalDaslParser result = new InternalDaslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAbstractElementAccess().getAlternatives(), "rule__AbstractElement__Alternatives");
					put(grammarAccess.getFlowEndpointAccess().getAlternatives(), "rule__FlowEndpoint__Alternatives");
					put(grammarAccess.getNodeTypeAccess().getAlternatives(), "rule__NodeType__Alternatives");
					put(grammarAccess.getControlTypeAccess().getAlternatives(), "rule__ControlType__Alternatives");
					put(grammarAccess.getConfidentialityTypeAccess().getAlternatives(), "rule__ConfidentialityType__Alternatives");
					put(grammarAccess.getIntegrityTypeAccess().getAlternatives(), "rule__IntegrityType__Alternatives");
					put(grammarAccess.getAvailabilityTypeAccess().getAlternatives(), "rule__AvailabilityType__Alternatives");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getQualifiedNameWithWildcardAccess().getGroup(), "rule__QualifiedNameWithWildcard__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getZoneAccess().getGroup(), "rule__Zone__Group__0");
					put(grammarAccess.getZoneAccess().getGroup_11(), "rule__Zone__Group_11__0");
					put(grammarAccess.getNodeAccess().getGroup(), "rule__Node__Group__0");
					put(grammarAccess.getNodeAccess().getGroup_11(), "rule__Node__Group_11__0");
					put(grammarAccess.getNodeAccess().getGroup_12(), "rule__Node__Group_12__0");
					put(grammarAccess.getNodeAccess().getGroup_13(), "rule__Node__Group_13__0");
					put(grammarAccess.getComponentAccess().getGroup(), "rule__Component__Group__0");
					put(grammarAccess.getComponentAccess().getGroup_7(), "rule__Component__Group_7__0");
					put(grammarAccess.getComponentAccess().getGroup_12(), "rule__Component__Group_12__0");
					put(grammarAccess.getComponentAccess().getGroup_13(), "rule__Component__Group_13__0");
					put(grammarAccess.getInformationAssetAccess().getGroup(), "rule__InformationAsset__Group__0");
					put(grammarAccess.getFlowAccess().getGroup(), "rule__Flow__Group__0");
					put(grammarAccess.getFlowAccess().getGroup_7(), "rule__Flow__Group_7__0");
					put(grammarAccess.getFlowAccess().getGroup_8(), "rule__Flow__Group_8__0");
					put(grammarAccess.getControlAccess().getGroup(), "rule__Control__Group__0");
					put(grammarAccess.getActorAccess().getGroup(), "rule__Actor__Group__0");
					put(grammarAccess.getSecurityModelAccess().getElementsAssignment(), "rule__SecurityModel__ElementsAssignment");
					put(grammarAccess.getImportAccess().getImportURIAssignment_1(), "rule__Import__ImportURIAssignment_1");
					put(grammarAccess.getZoneAccess().getNameAssignment_1(), "rule__Zone__NameAssignment_1");
					put(grammarAccess.getZoneAccess().getTrustAssignment_4(), "rule__Zone__TrustAssignment_4");
					put(grammarAccess.getZoneAccess().getIngressZonesAssignment_6(), "rule__Zone__IngressZonesAssignment_6");
					put(grammarAccess.getZoneAccess().getEgressZonesAssignment_8(), "rule__Zone__EgressZonesAssignment_8");
					put(grammarAccess.getZoneAccess().getNodesAssignment_10(), "rule__Zone__NodesAssignment_10");
					put(grammarAccess.getZoneAccess().getControlsAssignment_11_1(), "rule__Zone__ControlsAssignment_11_1");
					put(grammarAccess.getNodeAccess().getNameAssignment_1(), "rule__Node__NameAssignment_1");
					put(grammarAccess.getNodeAccess().getRefAssignment_4(), "rule__Node__RefAssignment_4");
					put(grammarAccess.getNodeAccess().getHostAssignment_6(), "rule__Node__HostAssignment_6");
					put(grammarAccess.getNodeAccess().getOsAssignment_8(), "rule__Node__OsAssignment_8");
					put(grammarAccess.getNodeAccess().getValueAssignment_10(), "rule__Node__ValueAssignment_10");
					put(grammarAccess.getNodeAccess().getComponentsAssignment_11_1(), "rule__Node__ComponentsAssignment_11_1");
					put(grammarAccess.getNodeAccess().getControlsAssignment_12_1(), "rule__Node__ControlsAssignment_12_1");
					put(grammarAccess.getNodeAccess().getAssetsAssignment_13_1(), "rule__Node__AssetsAssignment_13_1");
					put(grammarAccess.getComponentAccess().getNameAssignment_1(), "rule__Component__NameAssignment_1");
					put(grammarAccess.getComponentAccess().getRefAssignment_4(), "rule__Component__RefAssignment_4");
					put(grammarAccess.getComponentAccess().getStereotypeAssignment_6(), "rule__Component__StereotypeAssignment_6");
					put(grammarAccess.getComponentAccess().getVendorAssignment_7_1(), "rule__Component__VendorAssignment_7_1");
					put(grammarAccess.getComponentAccess().getDescAssignment_9(), "rule__Component__DescAssignment_9");
					put(grammarAccess.getComponentAccess().getVersionAssignment_11(), "rule__Component__VersionAssignment_11");
					put(grammarAccess.getComponentAccess().getAssetsAssignment_12_1(), "rule__Component__AssetsAssignment_12_1");
					put(grammarAccess.getComponentAccess().getControlsAssignment_13_1(), "rule__Component__ControlsAssignment_13_1");
					put(grammarAccess.getComponentAccess().getComponentsAssignment_14(), "rule__Component__ComponentsAssignment_14");
					put(grammarAccess.getInformationAssetAccess().getNameAssignment_1(), "rule__InformationAsset__NameAssignment_1");
					put(grammarAccess.getInformationAssetAccess().getRefAssignment_4(), "rule__InformationAsset__RefAssignment_4");
					put(grammarAccess.getInformationAssetAccess().getDescAssignment_6(), "rule__InformationAsset__DescAssignment_6");
					put(grammarAccess.getInformationAssetAccess().getConfidentialityAssignment_8(), "rule__InformationAsset__ConfidentialityAssignment_8");
					put(grammarAccess.getInformationAssetAccess().getIntegrityAssignment_10(), "rule__InformationAsset__IntegrityAssignment_10");
					put(grammarAccess.getInformationAssetAccess().getAvailabilityAssignment_12(), "rule__InformationAsset__AvailabilityAssignment_12");
					put(grammarAccess.getFlowAccess().getNameAssignment_1(), "rule__Flow__NameAssignment_1");
					put(grammarAccess.getFlowAccess().getFromAssignment_4(), "rule__Flow__FromAssignment_4");
					put(grammarAccess.getFlowAccess().getToAssignment_6(), "rule__Flow__ToAssignment_6");
					put(grammarAccess.getFlowAccess().getAssetsAssignment_7_1(), "rule__Flow__AssetsAssignment_7_1");
					put(grammarAccess.getFlowAccess().getControlsAssignment_8_1(), "rule__Flow__ControlsAssignment_8_1");
					put(grammarAccess.getControlAccess().getNameAssignment_1(), "rule__Control__NameAssignment_1");
					put(grammarAccess.getControlAccess().getRefAssignment_4(), "rule__Control__RefAssignment_4");
					put(grammarAccess.getControlAccess().getAreaAssignment_6(), "rule__Control__AreaAssignment_6");
					put(grammarAccess.getControlAccess().getImplementationAssignment_8(), "rule__Control__ImplementationAssignment_8");
					put(grammarAccess.getActorAccess().getNameAssignment_1(), "rule__Actor__NameAssignment_1");
					put(grammarAccess.getActorAccess().getDescAssignment_4(), "rule__Actor__DescAssignment_4");
					put(grammarAccess.getActorAccess().getRolesAssignment_6(), "rule__Actor__RolesAssignment_6");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DaslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DaslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
