/**
 * generated by Xtext 2.12.0
 */
package org.sabsa.dasl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.sabsa.dasl.ui.AbstractDaslUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DaslUiModule extends AbstractDaslUiModule {
  public DaslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
