/**
 * generated by Xtext 2.12.0
 */
package org.sabsa.dasl.validation;

import org.eclipse.xtext.validation.Check;
import org.sabsa.dasl.dasl.Flow;
import org.sabsa.dasl.dasl.Node;
import org.sabsa.dasl.validation.AbstractDaslValidator;
import org.sabsa.dasl.validation.Validator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DaslValidator extends AbstractDaslValidator {
  @Check
  public void checkFlowHasAtLeastOneInformationAsset(final Flow f) {
    boolean _doesFlowHaveAtLeastOneInformationAsset = Validator.doesFlowHaveAtLeastOneInformationAsset(f);
    boolean _not = (!_doesFlowHaveAtLeastOneInformationAsset);
    if (_not) {
      String _name = f.getName();
      String _plus = ("Flow " + _name);
      String _plus_1 = (_plus + " has no information assets");
      this.error(_plus_1, f, null);
    }
  }
  
  @Check
  public void checkFlowHasAtLeastOneControl(final Flow f) {
    int _size = f.getControls().size();
    boolean _greaterThan = (_size > 0);
    boolean _not = (!_greaterThan);
    if (_not) {
      String _name = f.getName();
      String _plus = ("Flow " + _name);
      String _plus_1 = (_plus + " has no controls");
      this.error(_plus_1, f, null);
    }
  }
  
  @Check
  public void checkAllNodesAreInAZone(final Node node) {
    boolean _isNodeInAtLeastOneZone = Validator.isNodeInAtLeastOneZone(node);
    boolean _not = (!_isNodeInAtLeastOneZone);
    if (_not) {
      String _name = node.getName();
      String _plus = ("Node " + _name);
      String _plus_1 = (_plus + " is not associated to any zone");
      this.error(_plus_1, node, null);
    }
  }
  
  @Check
  public void checkFlowDoesNotViolateZoneRules(final Flow f) {
    boolean _doesFlowViolateZoneRules = Validator.doesFlowViolateZoneRules(f);
    if (_doesFlowViolateZoneRules) {
      String _name = f.getName();
      String _plus = ("Flow " + _name);
      String _plus_1 = (_plus + " violates zone rules");
      this.error(_plus_1, f, null);
    }
  }
}
