/*
 * generated by Xtext 2.12.0
 */
package org.sabsa.dasl

import org.eclipse.xtext.scoping.IGlobalScopeProvider
import org.eclipse.xtext.scoping.impl.ImportUriGlobalScopeProvider

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DaslRuntimeModule extends AbstractDaslRuntimeModule {
	override def Class<? extends IGlobalScopeProvider>bindIGlobalScopeProvider() {
 		return typeof(ImportUriGlobalScopeProvider);
 	} 
 	
}
