/**
 * generated by Xtext 2.12.0
 */
package org.sabsa.dasl.dasl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Control Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.sabsa.dasl.dasl.DaslPackage#getControlType()
 * @model
 * @generated
 */
public enum ControlType implements Enumerator
{
  /**
   * The '<em><b>Identity Validation</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IDENTITY_VALIDATION_VALUE
   * @generated
   * @ordered
   */
  IDENTITY_VALIDATION(0, "IdentityValidation", "IdentityValidation"),

  /**
   * The '<em><b>User Provisioning</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #USER_PROVISIONING_VALUE
   * @generated
   * @ordered
   */
  USER_PROVISIONING(1, "UserProvisioning", "UserProvisioning"),

  /**
   * The '<em><b>System User Provisioning</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SYSTEM_USER_PROVISIONING_VALUE
   * @generated
   * @ordered
   */
  SYSTEM_USER_PROVISIONING(2, "SystemUserProvisioning", "SystemUserProvisioning"),

  /**
   * The '<em><b>Identity Transformation</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IDENTITY_TRANSFORMATION_VALUE
   * @generated
   * @ordered
   */
  IDENTITY_TRANSFORMATION(3, "IdentityTransformation", "IdentityTransformation"),

  /**
   * The '<em><b>User Registries</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #USER_REGISTRIES_VALUE
   * @generated
   * @ordered
   */
  USER_REGISTRIES(4, "UserRegistries", "UserRegistries"),

  /**
   * The '<em><b>Credential Management</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CREDENTIAL_MANAGEMENT_VALUE
   * @generated
   * @ordered
   */
  CREDENTIAL_MANAGEMENT(5, "CredentialManagement", "CredentialManagement"),

  /**
   * The '<em><b>Authentication</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AUTHENTICATION_VALUE
   * @generated
   * @ordered
   */
  AUTHENTICATION(6, "Authentication", "Authentication"),

  /**
   * The '<em><b>Authorisation</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AUTHORISATION_VALUE
   * @generated
   * @ordered
   */
  AUTHORISATION(7, "Authorisation", "Authorisation"),

  /**
   * The '<em><b>Privilege Management</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PRIVILEGE_MANAGEMENT_VALUE
   * @generated
   * @ordered
   */
  PRIVILEGE_MANAGEMENT(8, "PrivilegeManagement", "PrivilegeManagement"),

  /**
   * The '<em><b>Reduced Sign On</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REDUCED_SIGN_ON_VALUE
   * @generated
   * @ordered
   */
  REDUCED_SIGN_ON(9, "ReducedSignOn", "ReducedSignOn"),

  /**
   * The '<em><b>Federation</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FEDERATION_VALUE
   * @generated
   * @ordered
   */
  FEDERATION(10, "Federation", "Federation"),

  /**
   * The '<em><b>Access Entitlement Governance</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACCESS_ENTITLEMENT_GOVERNANCE_VALUE
   * @generated
   * @ordered
   */
  ACCESS_ENTITLEMENT_GOVERNANCE(11, "AccessEntitlementGovernance", "AccessEntitlementGovernance"),

  /**
   * The '<em><b>Firewalls Network</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FIREWALLS_NETWORK_VALUE
   * @generated
   * @ordered
   */
  FIREWALLS_NETWORK(12, "FirewallsNetwork", "FirewallsNetwork"),

  /**
   * The '<em><b>Firewalls Application</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FIREWALLS_APPLICATION_VALUE
   * @generated
   * @ordered
   */
  FIREWALLS_APPLICATION(13, "FirewallsApplication", "FirewallsApplication"),

  /**
   * The '<em><b>Denialof Service</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DENIALOF_SERVICE_VALUE
   * @generated
   * @ordered
   */
  DENIALOF_SERVICE(14, "DenialofService", "DenialofService"),

  /**
   * The '<em><b>Network Admission Control</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #NETWORK_ADMISSION_CONTROL_VALUE
   * @generated
   * @ordered
   */
  NETWORK_ADMISSION_CONTROL(15, "NetworkAdmissionControl", "NetworkAdmissionControl"),

  /**
   * The '<em><b>Remote Access Gateway</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #REMOTE_ACCESS_GATEWAY_VALUE
   * @generated
   * @ordered
   */
  REMOTE_ACCESS_GATEWAY(16, "RemoteAccessGateway", "RemoteAccessGateway"),

  /**
   * The '<em><b>Intrusion Prevention Detection</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INTRUSION_PREVENTION_DETECTION_VALUE
   * @generated
   * @ordered
   */
  INTRUSION_PREVENTION_DETECTION(17, "IntrusionPreventionDetection", "IntrusionPreventionDetection"),

  /**
   * The '<em><b>Antivirus</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ANTIVIRUS_VALUE
   * @generated
   * @ordered
   */
  ANTIVIRUS(18, "Antivirus", "Antivirus"),

  /**
   * The '<em><b>Content Filter</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CONTENT_FILTER_VALUE
   * @generated
   * @ordered
   */
  CONTENT_FILTER(19, "ContentFilter", "ContentFilter"),

  /**
   * The '<em><b>Message Security</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MESSAGE_SECURITY_VALUE
   * @generated
   * @ordered
   */
  MESSAGE_SECURITY(20, "MessageSecurity", "MessageSecurity"),

  /**
   * The '<em><b>Transport Security</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TRANSPORT_SECURITY_VALUE
   * @generated
   * @ordered
   */
  TRANSPORT_SECURITY(21, "TransportSecurity", "TransportSecurity"),

  /**
   * The '<em><b>Stored Data Security</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STORED_DATA_SECURITY_VALUE
   * @generated
   * @ordered
   */
  STORED_DATA_SECURITY(22, "StoredDataSecurity", "StoredDataSecurity"),

  /**
   * The '<em><b>Data Loss Prevention</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DATA_LOSS_PREVENTION_VALUE
   * @generated
   * @ordered
   */
  DATA_LOSS_PREVENTION(23, "DataLossPrevention", "DataLossPrevention"),

  /**
   * The '<em><b>Data Obfuscation</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DATA_OBFUSCATION_VALUE
   * @generated
   * @ordered
   */
  DATA_OBFUSCATION(24, "DataObfuscation", "DataObfuscation"),

  /**
   * The '<em><b>Data Destruction</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DATA_DESTRUCTION_VALUE
   * @generated
   * @ordered
   */
  DATA_DESTRUCTION(25, "DataDestruction", "DataDestruction"),

  /**
   * The '<em><b>Fraud Security</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FRAUD_SECURITY_VALUE
   * @generated
   * @ordered
   */
  FRAUD_SECURITY(26, "FraudSecurity", "FraudSecurity"),

  /**
   * The '<em><b>Data Transaction Security</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #DATA_TRANSACTION_SECURITY_VALUE
   * @generated
   * @ordered
   */
  DATA_TRANSACTION_SECURITY(27, "DataTransactionSecurity", "DataTransactionSecurity"),

  /**
   * The '<em><b>Centralised HSM CA PKI</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CENTRALISED_HSM_CA_PKI_VALUE
   * @generated
   * @ordered
   */
  CENTRALISED_HSM_CA_PKI(28, "CentralisedHSM_CA_PKI", "CentralisedHSM_CA_PKI"),

  /**
   * The '<em><b>Standalone</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STANDALONE_VALUE
   * @generated
   * @ordered
   */
  STANDALONE(29, "Standalone", "Standalone"),

  /**
   * The '<em><b>Security Testing</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SECURITY_TESTING_VALUE
   * @generated
   * @ordered
   */
  SECURITY_TESTING(30, "SecurityTesting", "SecurityTesting"),

  /**
   * The '<em><b>Patch Management</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PATCH_MANAGEMENT_VALUE
   * @generated
   * @ordered
   */
  PATCH_MANAGEMENT(31, "PatchManagement", "PatchManagement"),

  /**
   * The '<em><b>Vulnerability Management</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #VULNERABILITY_MANAGEMENT_VALUE
   * @generated
   * @ordered
   */
  VULNERABILITY_MANAGEMENT(32, "VulnerabilityManagement", "VulnerabilityManagement"),

  /**
   * The '<em><b>Centralised Reporting</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CENTRALISED_REPORTING_VALUE
   * @generated
   * @ordered
   */
  CENTRALISED_REPORTING(33, "CentralisedReporting", "CentralisedReporting"),

  /**
   * The '<em><b>Event Correlation</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #EVENT_CORRELATION_VALUE
   * @generated
   * @ordered
   */
  EVENT_CORRELATION(34, "EventCorrelation", "EventCorrelation"),

  /**
   * The '<em><b>Security Audit Log Monitoring</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SECURITY_AUDIT_LOG_MONITORING_VALUE
   * @generated
   * @ordered
   */
  SECURITY_AUDIT_LOG_MONITORING(35, "SecurityAuditLogMonitoring", "SecurityAuditLogMonitoring"),

  /**
   * The '<em><b>Compliance Testing</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #COMPLIANCE_TESTING_VALUE
   * @generated
   * @ordered
   */
  COMPLIANCE_TESTING(36, "ComplianceTesting", "ComplianceTesting"),

  /**
   * The '<em><b>Incident Management</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INCIDENT_MANAGEMENT_VALUE
   * @generated
   * @ordered
   */
  INCIDENT_MANAGEMENT(37, "IncidentManagement", "IncidentManagement"),

  /**
   * The '<em><b>Forensic</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FORENSIC_VALUE
   * @generated
   * @ordered
   */
  FORENSIC(38, "Forensic", "Forensic"),

  /**
   * The '<em><b>Legal</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LEGAL_VALUE
   * @generated
   * @ordered
   */
  LEGAL(39, "Legal", "Legal");

  /**
   * The '<em><b>Identity Validation</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Identity Validation</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #IDENTITY_VALIDATION
   * @model name="IdentityValidation"
   * @generated
   * @ordered
   */
  public static final int IDENTITY_VALIDATION_VALUE = 0;

  /**
   * The '<em><b>User Provisioning</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>User Provisioning</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #USER_PROVISIONING
   * @model name="UserProvisioning"
   * @generated
   * @ordered
   */
  public static final int USER_PROVISIONING_VALUE = 1;

  /**
   * The '<em><b>System User Provisioning</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>System User Provisioning</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SYSTEM_USER_PROVISIONING
   * @model name="SystemUserProvisioning"
   * @generated
   * @ordered
   */
  public static final int SYSTEM_USER_PROVISIONING_VALUE = 2;

  /**
   * The '<em><b>Identity Transformation</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Identity Transformation</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #IDENTITY_TRANSFORMATION
   * @model name="IdentityTransformation"
   * @generated
   * @ordered
   */
  public static final int IDENTITY_TRANSFORMATION_VALUE = 3;

  /**
   * The '<em><b>User Registries</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>User Registries</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #USER_REGISTRIES
   * @model name="UserRegistries"
   * @generated
   * @ordered
   */
  public static final int USER_REGISTRIES_VALUE = 4;

  /**
   * The '<em><b>Credential Management</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Credential Management</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CREDENTIAL_MANAGEMENT
   * @model name="CredentialManagement"
   * @generated
   * @ordered
   */
  public static final int CREDENTIAL_MANAGEMENT_VALUE = 5;

  /**
   * The '<em><b>Authentication</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Authentication</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #AUTHENTICATION
   * @model name="Authentication"
   * @generated
   * @ordered
   */
  public static final int AUTHENTICATION_VALUE = 6;

  /**
   * The '<em><b>Authorisation</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Authorisation</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #AUTHORISATION
   * @model name="Authorisation"
   * @generated
   * @ordered
   */
  public static final int AUTHORISATION_VALUE = 7;

  /**
   * The '<em><b>Privilege Management</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Privilege Management</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PRIVILEGE_MANAGEMENT
   * @model name="PrivilegeManagement"
   * @generated
   * @ordered
   */
  public static final int PRIVILEGE_MANAGEMENT_VALUE = 8;

  /**
   * The '<em><b>Reduced Sign On</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Reduced Sign On</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #REDUCED_SIGN_ON
   * @model name="ReducedSignOn"
   * @generated
   * @ordered
   */
  public static final int REDUCED_SIGN_ON_VALUE = 9;

  /**
   * The '<em><b>Federation</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Federation</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FEDERATION
   * @model name="Federation"
   * @generated
   * @ordered
   */
  public static final int FEDERATION_VALUE = 10;

  /**
   * The '<em><b>Access Entitlement Governance</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Access Entitlement Governance</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ACCESS_ENTITLEMENT_GOVERNANCE
   * @model name="AccessEntitlementGovernance"
   * @generated
   * @ordered
   */
  public static final int ACCESS_ENTITLEMENT_GOVERNANCE_VALUE = 11;

  /**
   * The '<em><b>Firewalls Network</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Firewalls Network</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FIREWALLS_NETWORK
   * @model name="FirewallsNetwork"
   * @generated
   * @ordered
   */
  public static final int FIREWALLS_NETWORK_VALUE = 12;

  /**
   * The '<em><b>Firewalls Application</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Firewalls Application</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FIREWALLS_APPLICATION
   * @model name="FirewallsApplication"
   * @generated
   * @ordered
   */
  public static final int FIREWALLS_APPLICATION_VALUE = 13;

  /**
   * The '<em><b>Denialof Service</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Denialof Service</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DENIALOF_SERVICE
   * @model name="DenialofService"
   * @generated
   * @ordered
   */
  public static final int DENIALOF_SERVICE_VALUE = 14;

  /**
   * The '<em><b>Network Admission Control</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Network Admission Control</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #NETWORK_ADMISSION_CONTROL
   * @model name="NetworkAdmissionControl"
   * @generated
   * @ordered
   */
  public static final int NETWORK_ADMISSION_CONTROL_VALUE = 15;

  /**
   * The '<em><b>Remote Access Gateway</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Remote Access Gateway</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #REMOTE_ACCESS_GATEWAY
   * @model name="RemoteAccessGateway"
   * @generated
   * @ordered
   */
  public static final int REMOTE_ACCESS_GATEWAY_VALUE = 16;

  /**
   * The '<em><b>Intrusion Prevention Detection</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Intrusion Prevention Detection</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INTRUSION_PREVENTION_DETECTION
   * @model name="IntrusionPreventionDetection"
   * @generated
   * @ordered
   */
  public static final int INTRUSION_PREVENTION_DETECTION_VALUE = 17;

  /**
   * The '<em><b>Antivirus</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Antivirus</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ANTIVIRUS
   * @model name="Antivirus"
   * @generated
   * @ordered
   */
  public static final int ANTIVIRUS_VALUE = 18;

  /**
   * The '<em><b>Content Filter</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Content Filter</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CONTENT_FILTER
   * @model name="ContentFilter"
   * @generated
   * @ordered
   */
  public static final int CONTENT_FILTER_VALUE = 19;

  /**
   * The '<em><b>Message Security</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Message Security</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #MESSAGE_SECURITY
   * @model name="MessageSecurity"
   * @generated
   * @ordered
   */
  public static final int MESSAGE_SECURITY_VALUE = 20;

  /**
   * The '<em><b>Transport Security</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Transport Security</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TRANSPORT_SECURITY
   * @model name="TransportSecurity"
   * @generated
   * @ordered
   */
  public static final int TRANSPORT_SECURITY_VALUE = 21;

  /**
   * The '<em><b>Stored Data Security</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Stored Data Security</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #STORED_DATA_SECURITY
   * @model name="StoredDataSecurity"
   * @generated
   * @ordered
   */
  public static final int STORED_DATA_SECURITY_VALUE = 22;

  /**
   * The '<em><b>Data Loss Prevention</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Data Loss Prevention</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DATA_LOSS_PREVENTION
   * @model name="DataLossPrevention"
   * @generated
   * @ordered
   */
  public static final int DATA_LOSS_PREVENTION_VALUE = 23;

  /**
   * The '<em><b>Data Obfuscation</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Data Obfuscation</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DATA_OBFUSCATION
   * @model name="DataObfuscation"
   * @generated
   * @ordered
   */
  public static final int DATA_OBFUSCATION_VALUE = 24;

  /**
   * The '<em><b>Data Destruction</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Data Destruction</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DATA_DESTRUCTION
   * @model name="DataDestruction"
   * @generated
   * @ordered
   */
  public static final int DATA_DESTRUCTION_VALUE = 25;

  /**
   * The '<em><b>Fraud Security</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Fraud Security</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FRAUD_SECURITY
   * @model name="FraudSecurity"
   * @generated
   * @ordered
   */
  public static final int FRAUD_SECURITY_VALUE = 26;

  /**
   * The '<em><b>Data Transaction Security</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Data Transaction Security</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #DATA_TRANSACTION_SECURITY
   * @model name="DataTransactionSecurity"
   * @generated
   * @ordered
   */
  public static final int DATA_TRANSACTION_SECURITY_VALUE = 27;

  /**
   * The '<em><b>Centralised HSM CA PKI</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Centralised HSM CA PKI</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CENTRALISED_HSM_CA_PKI
   * @model name="CentralisedHSM_CA_PKI"
   * @generated
   * @ordered
   */
  public static final int CENTRALISED_HSM_CA_PKI_VALUE = 28;

  /**
   * The '<em><b>Standalone</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Standalone</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #STANDALONE
   * @model name="Standalone"
   * @generated
   * @ordered
   */
  public static final int STANDALONE_VALUE = 29;

  /**
   * The '<em><b>Security Testing</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Security Testing</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SECURITY_TESTING
   * @model name="SecurityTesting"
   * @generated
   * @ordered
   */
  public static final int SECURITY_TESTING_VALUE = 30;

  /**
   * The '<em><b>Patch Management</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Patch Management</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #PATCH_MANAGEMENT
   * @model name="PatchManagement"
   * @generated
   * @ordered
   */
  public static final int PATCH_MANAGEMENT_VALUE = 31;

  /**
   * The '<em><b>Vulnerability Management</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Vulnerability Management</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #VULNERABILITY_MANAGEMENT
   * @model name="VulnerabilityManagement"
   * @generated
   * @ordered
   */
  public static final int VULNERABILITY_MANAGEMENT_VALUE = 32;

  /**
   * The '<em><b>Centralised Reporting</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Centralised Reporting</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #CENTRALISED_REPORTING
   * @model name="CentralisedReporting"
   * @generated
   * @ordered
   */
  public static final int CENTRALISED_REPORTING_VALUE = 33;

  /**
   * The '<em><b>Event Correlation</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Event Correlation</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #EVENT_CORRELATION
   * @model name="EventCorrelation"
   * @generated
   * @ordered
   */
  public static final int EVENT_CORRELATION_VALUE = 34;

  /**
   * The '<em><b>Security Audit Log Monitoring</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Security Audit Log Monitoring</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #SECURITY_AUDIT_LOG_MONITORING
   * @model name="SecurityAuditLogMonitoring"
   * @generated
   * @ordered
   */
  public static final int SECURITY_AUDIT_LOG_MONITORING_VALUE = 35;

  /**
   * The '<em><b>Compliance Testing</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Compliance Testing</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #COMPLIANCE_TESTING
   * @model name="ComplianceTesting"
   * @generated
   * @ordered
   */
  public static final int COMPLIANCE_TESTING_VALUE = 36;

  /**
   * The '<em><b>Incident Management</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Incident Management</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #INCIDENT_MANAGEMENT
   * @model name="IncidentManagement"
   * @generated
   * @ordered
   */
  public static final int INCIDENT_MANAGEMENT_VALUE = 37;

  /**
   * The '<em><b>Forensic</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Forensic</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #FORENSIC
   * @model name="Forensic"
   * @generated
   * @ordered
   */
  public static final int FORENSIC_VALUE = 38;

  /**
   * The '<em><b>Legal</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Legal</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #LEGAL
   * @model name="Legal"
   * @generated
   * @ordered
   */
  public static final int LEGAL_VALUE = 39;

  /**
   * An array of all the '<em><b>Control Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ControlType[] VALUES_ARRAY =
    new ControlType[]
    {
      IDENTITY_VALIDATION,
      USER_PROVISIONING,
      SYSTEM_USER_PROVISIONING,
      IDENTITY_TRANSFORMATION,
      USER_REGISTRIES,
      CREDENTIAL_MANAGEMENT,
      AUTHENTICATION,
      AUTHORISATION,
      PRIVILEGE_MANAGEMENT,
      REDUCED_SIGN_ON,
      FEDERATION,
      ACCESS_ENTITLEMENT_GOVERNANCE,
      FIREWALLS_NETWORK,
      FIREWALLS_APPLICATION,
      DENIALOF_SERVICE,
      NETWORK_ADMISSION_CONTROL,
      REMOTE_ACCESS_GATEWAY,
      INTRUSION_PREVENTION_DETECTION,
      ANTIVIRUS,
      CONTENT_FILTER,
      MESSAGE_SECURITY,
      TRANSPORT_SECURITY,
      STORED_DATA_SECURITY,
      DATA_LOSS_PREVENTION,
      DATA_OBFUSCATION,
      DATA_DESTRUCTION,
      FRAUD_SECURITY,
      DATA_TRANSACTION_SECURITY,
      CENTRALISED_HSM_CA_PKI,
      STANDALONE,
      SECURITY_TESTING,
      PATCH_MANAGEMENT,
      VULNERABILITY_MANAGEMENT,
      CENTRALISED_REPORTING,
      EVENT_CORRELATION,
      SECURITY_AUDIT_LOG_MONITORING,
      COMPLIANCE_TESTING,
      INCIDENT_MANAGEMENT,
      FORENSIC,
      LEGAL,
    };

  /**
   * A public read-only list of all the '<em><b>Control Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ControlType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Control Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ControlType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ControlType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Control Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ControlType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ControlType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Control Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ControlType get(int value)
  {
    switch (value)
    {
      case IDENTITY_VALIDATION_VALUE: return IDENTITY_VALIDATION;
      case USER_PROVISIONING_VALUE: return USER_PROVISIONING;
      case SYSTEM_USER_PROVISIONING_VALUE: return SYSTEM_USER_PROVISIONING;
      case IDENTITY_TRANSFORMATION_VALUE: return IDENTITY_TRANSFORMATION;
      case USER_REGISTRIES_VALUE: return USER_REGISTRIES;
      case CREDENTIAL_MANAGEMENT_VALUE: return CREDENTIAL_MANAGEMENT;
      case AUTHENTICATION_VALUE: return AUTHENTICATION;
      case AUTHORISATION_VALUE: return AUTHORISATION;
      case PRIVILEGE_MANAGEMENT_VALUE: return PRIVILEGE_MANAGEMENT;
      case REDUCED_SIGN_ON_VALUE: return REDUCED_SIGN_ON;
      case FEDERATION_VALUE: return FEDERATION;
      case ACCESS_ENTITLEMENT_GOVERNANCE_VALUE: return ACCESS_ENTITLEMENT_GOVERNANCE;
      case FIREWALLS_NETWORK_VALUE: return FIREWALLS_NETWORK;
      case FIREWALLS_APPLICATION_VALUE: return FIREWALLS_APPLICATION;
      case DENIALOF_SERVICE_VALUE: return DENIALOF_SERVICE;
      case NETWORK_ADMISSION_CONTROL_VALUE: return NETWORK_ADMISSION_CONTROL;
      case REMOTE_ACCESS_GATEWAY_VALUE: return REMOTE_ACCESS_GATEWAY;
      case INTRUSION_PREVENTION_DETECTION_VALUE: return INTRUSION_PREVENTION_DETECTION;
      case ANTIVIRUS_VALUE: return ANTIVIRUS;
      case CONTENT_FILTER_VALUE: return CONTENT_FILTER;
      case MESSAGE_SECURITY_VALUE: return MESSAGE_SECURITY;
      case TRANSPORT_SECURITY_VALUE: return TRANSPORT_SECURITY;
      case STORED_DATA_SECURITY_VALUE: return STORED_DATA_SECURITY;
      case DATA_LOSS_PREVENTION_VALUE: return DATA_LOSS_PREVENTION;
      case DATA_OBFUSCATION_VALUE: return DATA_OBFUSCATION;
      case DATA_DESTRUCTION_VALUE: return DATA_DESTRUCTION;
      case FRAUD_SECURITY_VALUE: return FRAUD_SECURITY;
      case DATA_TRANSACTION_SECURITY_VALUE: return DATA_TRANSACTION_SECURITY;
      case CENTRALISED_HSM_CA_PKI_VALUE: return CENTRALISED_HSM_CA_PKI;
      case STANDALONE_VALUE: return STANDALONE;
      case SECURITY_TESTING_VALUE: return SECURITY_TESTING;
      case PATCH_MANAGEMENT_VALUE: return PATCH_MANAGEMENT;
      case VULNERABILITY_MANAGEMENT_VALUE: return VULNERABILITY_MANAGEMENT;
      case CENTRALISED_REPORTING_VALUE: return CENTRALISED_REPORTING;
      case EVENT_CORRELATION_VALUE: return EVENT_CORRELATION;
      case SECURITY_AUDIT_LOG_MONITORING_VALUE: return SECURITY_AUDIT_LOG_MONITORING;
      case COMPLIANCE_TESTING_VALUE: return COMPLIANCE_TESTING;
      case INCIDENT_MANAGEMENT_VALUE: return INCIDENT_MANAGEMENT;
      case FORENSIC_VALUE: return FORENSIC;
      case LEGAL_VALUE: return LEGAL;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ControlType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ControlType
