/**
 * generated by Xtext 2.12.0
 */
package org.sabsa.dasl.dasl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.sabsa.dasl.dasl.DaslFactory
 * @model kind="package"
 * @generated
 */
public interface DaslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dasl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.sabsa.org/dasl/Dasl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dasl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DaslPackage eINSTANCE = org.sabsa.dasl.dasl.impl.DaslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.impl.SecurityModelImpl <em>Security Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.impl.SecurityModelImpl
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getSecurityModel()
   * @generated
   */
  int SECURITY_MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECURITY_MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Security Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SECURITY_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.impl.AbstractElementImpl
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 9;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.impl.ImportImpl
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 1;

  /**
   * The feature id for the '<em><b>Import URI</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORT_URI = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.impl.ZoneImpl <em>Zone</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.impl.ZoneImpl
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getZone()
   * @generated
   */
  int ZONE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZONE__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Trust</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZONE__TRUST = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Ingress Zones</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZONE__INGRESS_ZONES = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Egress Zones</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZONE__EGRESS_ZONES = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Nodes</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZONE__NODES = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Controls</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZONE__CONTROLS = ABSTRACT_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Zone</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ZONE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.impl.NodeImpl <em>Node</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.impl.NodeImpl
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getNode()
   * @generated
   */
  int NODE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__REF = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Host</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__HOST = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Os</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__OS = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__VALUE = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Components</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__COMPONENTS = ABSTRACT_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Controls</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__CONTROLS = ABSTRACT_ELEMENT_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Assets</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE__ASSETS = ABSTRACT_ELEMENT_FEATURE_COUNT + 7;

  /**
   * The number of structural features of the '<em>Node</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 8;

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.impl.ComponentImpl
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__REF = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Stereotype</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__STEREOTYPE = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Vendor</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__VENDOR = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Desc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__DESC = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Version</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__VERSION = ABSTRACT_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The feature id for the '<em><b>Assets</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__ASSETS = ABSTRACT_ELEMENT_FEATURE_COUNT + 6;

  /**
   * The feature id for the '<em><b>Controls</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__CONTROLS = ABSTRACT_ELEMENT_FEATURE_COUNT + 7;

  /**
   * The feature id for the '<em><b>Components</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__COMPONENTS = ABSTRACT_ELEMENT_FEATURE_COUNT + 8;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 9;

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.impl.InformationAssetImpl <em>Information Asset</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.impl.InformationAssetImpl
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getInformationAsset()
   * @generated
   */
  int INFORMATION_ASSET = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INFORMATION_ASSET__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INFORMATION_ASSET__REF = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Desc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INFORMATION_ASSET__DESC = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Confidentiality</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INFORMATION_ASSET__CONFIDENTIALITY = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Integrity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INFORMATION_ASSET__INTEGRITY = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The feature id for the '<em><b>Availability</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INFORMATION_ASSET__AVAILABILITY = ABSTRACT_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The number of structural features of the '<em>Information Asset</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INFORMATION_ASSET_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 6;

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.impl.FlowImpl <em>Flow</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.impl.FlowImpl
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getFlow()
   * @generated
   */
  int FLOW = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOW__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOW__FROM = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOW__TO = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Assets</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOW__ASSETS = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Controls</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOW__CONTROLS = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Flow</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOW_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.impl.ControlImpl <em>Control</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.impl.ControlImpl
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getControl()
   * @generated
   */
  int CONTROL = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL__REF = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Area</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL__AREA = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Implementation</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL__IMPLEMENTATION = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Control</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTROL_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.impl.ActorImpl <em>Actor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.impl.ActorImpl
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getActor()
   * @generated
   */
  int ACTOR = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__NAME = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Desc</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__DESC = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Roles</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR__ROLES = ABSTRACT_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Actor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTOR_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.impl.FlowEndpointImpl <em>Flow Endpoint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.impl.FlowEndpointImpl
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getFlowEndpoint()
   * @generated
   */
  int FLOW_ENDPOINT = 10;

  /**
   * The number of structural features of the '<em>Flow Endpoint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FLOW_ENDPOINT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.NodeType <em>Node Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.NodeType
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getNodeType()
   * @generated
   */
  int NODE_TYPE = 11;

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.ControlType <em>Control Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.ControlType
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getControlType()
   * @generated
   */
  int CONTROL_TYPE = 12;

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.ConfidentialityType <em>Confidentiality Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.ConfidentialityType
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getConfidentialityType()
   * @generated
   */
  int CONFIDENTIALITY_TYPE = 13;

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.IntegrityType <em>Integrity Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.IntegrityType
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getIntegrityType()
   * @generated
   */
  int INTEGRITY_TYPE = 14;

  /**
   * The meta object id for the '{@link org.sabsa.dasl.dasl.AvailabilityType <em>Availability Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.sabsa.dasl.dasl.AvailabilityType
   * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getAvailabilityType()
   * @generated
   */
  int AVAILABILITY_TYPE = 15;


  /**
   * Returns the meta object for class '{@link org.sabsa.dasl.dasl.SecurityModel <em>Security Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Security Model</em>'.
   * @see org.sabsa.dasl.dasl.SecurityModel
   * @generated
   */
  EClass getSecurityModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.sabsa.dasl.dasl.SecurityModel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.sabsa.dasl.dasl.SecurityModel#getElements()
   * @see #getSecurityModel()
   * @generated
   */
  EReference getSecurityModel_Elements();

  /**
   * Returns the meta object for class '{@link org.sabsa.dasl.dasl.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see org.sabsa.dasl.dasl.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Import#getImportURI <em>Import URI</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Import URI</em>'.
   * @see org.sabsa.dasl.dasl.Import#getImportURI()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportURI();

  /**
   * Returns the meta object for class '{@link org.sabsa.dasl.dasl.Zone <em>Zone</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Zone</em>'.
   * @see org.sabsa.dasl.dasl.Zone
   * @generated
   */
  EClass getZone();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Zone#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.sabsa.dasl.dasl.Zone#getName()
   * @see #getZone()
   * @generated
   */
  EAttribute getZone_Name();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Zone#getTrust <em>Trust</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Trust</em>'.
   * @see org.sabsa.dasl.dasl.Zone#getTrust()
   * @see #getZone()
   * @generated
   */
  EAttribute getZone_Trust();

  /**
   * Returns the meta object for the reference list '{@link org.sabsa.dasl.dasl.Zone#getIngressZones <em>Ingress Zones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Ingress Zones</em>'.
   * @see org.sabsa.dasl.dasl.Zone#getIngressZones()
   * @see #getZone()
   * @generated
   */
  EReference getZone_IngressZones();

  /**
   * Returns the meta object for the reference list '{@link org.sabsa.dasl.dasl.Zone#getEgressZones <em>Egress Zones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Egress Zones</em>'.
   * @see org.sabsa.dasl.dasl.Zone#getEgressZones()
   * @see #getZone()
   * @generated
   */
  EReference getZone_EgressZones();

  /**
   * Returns the meta object for the reference list '{@link org.sabsa.dasl.dasl.Zone#getNodes <em>Nodes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Nodes</em>'.
   * @see org.sabsa.dasl.dasl.Zone#getNodes()
   * @see #getZone()
   * @generated
   */
  EReference getZone_Nodes();

  /**
   * Returns the meta object for the reference list '{@link org.sabsa.dasl.dasl.Zone#getControls <em>Controls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Controls</em>'.
   * @see org.sabsa.dasl.dasl.Zone#getControls()
   * @see #getZone()
   * @generated
   */
  EReference getZone_Controls();

  /**
   * Returns the meta object for class '{@link org.sabsa.dasl.dasl.Node <em>Node</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node</em>'.
   * @see org.sabsa.dasl.dasl.Node
   * @generated
   */
  EClass getNode();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Node#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.sabsa.dasl.dasl.Node#getName()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Name();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Node#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ref</em>'.
   * @see org.sabsa.dasl.dasl.Node#getRef()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Ref();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Node#getHost <em>Host</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Host</em>'.
   * @see org.sabsa.dasl.dasl.Node#getHost()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Host();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Node#getOs <em>Os</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Os</em>'.
   * @see org.sabsa.dasl.dasl.Node#getOs()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Os();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Node#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.sabsa.dasl.dasl.Node#getValue()
   * @see #getNode()
   * @generated
   */
  EAttribute getNode_Value();

  /**
   * Returns the meta object for the reference list '{@link org.sabsa.dasl.dasl.Node#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Components</em>'.
   * @see org.sabsa.dasl.dasl.Node#getComponents()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Components();

  /**
   * Returns the meta object for the reference list '{@link org.sabsa.dasl.dasl.Node#getControls <em>Controls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Controls</em>'.
   * @see org.sabsa.dasl.dasl.Node#getControls()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Controls();

  /**
   * Returns the meta object for the reference list '{@link org.sabsa.dasl.dasl.Node#getAssets <em>Assets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Assets</em>'.
   * @see org.sabsa.dasl.dasl.Node#getAssets()
   * @see #getNode()
   * @generated
   */
  EReference getNode_Assets();

  /**
   * Returns the meta object for class '{@link org.sabsa.dasl.dasl.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see org.sabsa.dasl.dasl.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Component#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.sabsa.dasl.dasl.Component#getName()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_Name();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Component#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ref</em>'.
   * @see org.sabsa.dasl.dasl.Component#getRef()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_Ref();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Component#getStereotype <em>Stereotype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Stereotype</em>'.
   * @see org.sabsa.dasl.dasl.Component#getStereotype()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_Stereotype();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Component#getVendor <em>Vendor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vendor</em>'.
   * @see org.sabsa.dasl.dasl.Component#getVendor()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_Vendor();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Component#getDesc <em>Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Desc</em>'.
   * @see org.sabsa.dasl.dasl.Component#getDesc()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_Desc();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Component#getVersion <em>Version</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Version</em>'.
   * @see org.sabsa.dasl.dasl.Component#getVersion()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_Version();

  /**
   * Returns the meta object for the reference list '{@link org.sabsa.dasl.dasl.Component#getAssets <em>Assets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Assets</em>'.
   * @see org.sabsa.dasl.dasl.Component#getAssets()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Assets();

  /**
   * Returns the meta object for the reference list '{@link org.sabsa.dasl.dasl.Component#getControls <em>Controls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Controls</em>'.
   * @see org.sabsa.dasl.dasl.Component#getControls()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Controls();

  /**
   * Returns the meta object for the containment reference list '{@link org.sabsa.dasl.dasl.Component#getComponents <em>Components</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Components</em>'.
   * @see org.sabsa.dasl.dasl.Component#getComponents()
   * @see #getComponent()
   * @generated
   */
  EReference getComponent_Components();

  /**
   * Returns the meta object for class '{@link org.sabsa.dasl.dasl.InformationAsset <em>Information Asset</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Information Asset</em>'.
   * @see org.sabsa.dasl.dasl.InformationAsset
   * @generated
   */
  EClass getInformationAsset();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.InformationAsset#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.sabsa.dasl.dasl.InformationAsset#getName()
   * @see #getInformationAsset()
   * @generated
   */
  EAttribute getInformationAsset_Name();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.InformationAsset#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ref</em>'.
   * @see org.sabsa.dasl.dasl.InformationAsset#getRef()
   * @see #getInformationAsset()
   * @generated
   */
  EAttribute getInformationAsset_Ref();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.InformationAsset#getDesc <em>Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Desc</em>'.
   * @see org.sabsa.dasl.dasl.InformationAsset#getDesc()
   * @see #getInformationAsset()
   * @generated
   */
  EAttribute getInformationAsset_Desc();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.InformationAsset#getConfidentiality <em>Confidentiality</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Confidentiality</em>'.
   * @see org.sabsa.dasl.dasl.InformationAsset#getConfidentiality()
   * @see #getInformationAsset()
   * @generated
   */
  EAttribute getInformationAsset_Confidentiality();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.InformationAsset#getIntegrity <em>Integrity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Integrity</em>'.
   * @see org.sabsa.dasl.dasl.InformationAsset#getIntegrity()
   * @see #getInformationAsset()
   * @generated
   */
  EAttribute getInformationAsset_Integrity();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.InformationAsset#getAvailability <em>Availability</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Availability</em>'.
   * @see org.sabsa.dasl.dasl.InformationAsset#getAvailability()
   * @see #getInformationAsset()
   * @generated
   */
  EAttribute getInformationAsset_Availability();

  /**
   * Returns the meta object for class '{@link org.sabsa.dasl.dasl.Flow <em>Flow</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flow</em>'.
   * @see org.sabsa.dasl.dasl.Flow
   * @generated
   */
  EClass getFlow();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Flow#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.sabsa.dasl.dasl.Flow#getName()
   * @see #getFlow()
   * @generated
   */
  EAttribute getFlow_Name();

  /**
   * Returns the meta object for the reference '{@link org.sabsa.dasl.dasl.Flow#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>From</em>'.
   * @see org.sabsa.dasl.dasl.Flow#getFrom()
   * @see #getFlow()
   * @generated
   */
  EReference getFlow_From();

  /**
   * Returns the meta object for the reference '{@link org.sabsa.dasl.dasl.Flow#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>To</em>'.
   * @see org.sabsa.dasl.dasl.Flow#getTo()
   * @see #getFlow()
   * @generated
   */
  EReference getFlow_To();

  /**
   * Returns the meta object for the reference list '{@link org.sabsa.dasl.dasl.Flow#getAssets <em>Assets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Assets</em>'.
   * @see org.sabsa.dasl.dasl.Flow#getAssets()
   * @see #getFlow()
   * @generated
   */
  EReference getFlow_Assets();

  /**
   * Returns the meta object for the reference list '{@link org.sabsa.dasl.dasl.Flow#getControls <em>Controls</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Controls</em>'.
   * @see org.sabsa.dasl.dasl.Flow#getControls()
   * @see #getFlow()
   * @generated
   */
  EReference getFlow_Controls();

  /**
   * Returns the meta object for class '{@link org.sabsa.dasl.dasl.Control <em>Control</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Control</em>'.
   * @see org.sabsa.dasl.dasl.Control
   * @generated
   */
  EClass getControl();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Control#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.sabsa.dasl.dasl.Control#getName()
   * @see #getControl()
   * @generated
   */
  EAttribute getControl_Name();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Control#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ref</em>'.
   * @see org.sabsa.dasl.dasl.Control#getRef()
   * @see #getControl()
   * @generated
   */
  EAttribute getControl_Ref();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Control#getArea <em>Area</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Area</em>'.
   * @see org.sabsa.dasl.dasl.Control#getArea()
   * @see #getControl()
   * @generated
   */
  EAttribute getControl_Area();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Control#getImplementation <em>Implementation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Implementation</em>'.
   * @see org.sabsa.dasl.dasl.Control#getImplementation()
   * @see #getControl()
   * @generated
   */
  EAttribute getControl_Implementation();

  /**
   * Returns the meta object for class '{@link org.sabsa.dasl.dasl.Actor <em>Actor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actor</em>'.
   * @see org.sabsa.dasl.dasl.Actor
   * @generated
   */
  EClass getActor();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Actor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.sabsa.dasl.dasl.Actor#getName()
   * @see #getActor()
   * @generated
   */
  EAttribute getActor_Name();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Actor#getDesc <em>Desc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Desc</em>'.
   * @see org.sabsa.dasl.dasl.Actor#getDesc()
   * @see #getActor()
   * @generated
   */
  EAttribute getActor_Desc();

  /**
   * Returns the meta object for the attribute '{@link org.sabsa.dasl.dasl.Actor#getRoles <em>Roles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Roles</em>'.
   * @see org.sabsa.dasl.dasl.Actor#getRoles()
   * @see #getActor()
   * @generated
   */
  EAttribute getActor_Roles();

  /**
   * Returns the meta object for class '{@link org.sabsa.dasl.dasl.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see org.sabsa.dasl.dasl.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for class '{@link org.sabsa.dasl.dasl.FlowEndpoint <em>Flow Endpoint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Flow Endpoint</em>'.
   * @see org.sabsa.dasl.dasl.FlowEndpoint
   * @generated
   */
  EClass getFlowEndpoint();

  /**
   * Returns the meta object for enum '{@link org.sabsa.dasl.dasl.NodeType <em>Node Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Node Type</em>'.
   * @see org.sabsa.dasl.dasl.NodeType
   * @generated
   */
  EEnum getNodeType();

  /**
   * Returns the meta object for enum '{@link org.sabsa.dasl.dasl.ControlType <em>Control Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Control Type</em>'.
   * @see org.sabsa.dasl.dasl.ControlType
   * @generated
   */
  EEnum getControlType();

  /**
   * Returns the meta object for enum '{@link org.sabsa.dasl.dasl.ConfidentialityType <em>Confidentiality Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Confidentiality Type</em>'.
   * @see org.sabsa.dasl.dasl.ConfidentialityType
   * @generated
   */
  EEnum getConfidentialityType();

  /**
   * Returns the meta object for enum '{@link org.sabsa.dasl.dasl.IntegrityType <em>Integrity Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Integrity Type</em>'.
   * @see org.sabsa.dasl.dasl.IntegrityType
   * @generated
   */
  EEnum getIntegrityType();

  /**
   * Returns the meta object for enum '{@link org.sabsa.dasl.dasl.AvailabilityType <em>Availability Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Availability Type</em>'.
   * @see org.sabsa.dasl.dasl.AvailabilityType
   * @generated
   */
  EEnum getAvailabilityType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DaslFactory getDaslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.impl.SecurityModelImpl <em>Security Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.impl.SecurityModelImpl
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getSecurityModel()
     * @generated
     */
    EClass SECURITY_MODEL = eINSTANCE.getSecurityModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SECURITY_MODEL__ELEMENTS = eINSTANCE.getSecurityModel_Elements();

    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.impl.ImportImpl
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Import URI</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORT_URI = eINSTANCE.getImport_ImportURI();

    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.impl.ZoneImpl <em>Zone</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.impl.ZoneImpl
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getZone()
     * @generated
     */
    EClass ZONE = eINSTANCE.getZone();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZONE__NAME = eINSTANCE.getZone_Name();

    /**
     * The meta object literal for the '<em><b>Trust</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ZONE__TRUST = eINSTANCE.getZone_Trust();

    /**
     * The meta object literal for the '<em><b>Ingress Zones</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ZONE__INGRESS_ZONES = eINSTANCE.getZone_IngressZones();

    /**
     * The meta object literal for the '<em><b>Egress Zones</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ZONE__EGRESS_ZONES = eINSTANCE.getZone_EgressZones();

    /**
     * The meta object literal for the '<em><b>Nodes</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ZONE__NODES = eINSTANCE.getZone_Nodes();

    /**
     * The meta object literal for the '<em><b>Controls</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ZONE__CONTROLS = eINSTANCE.getZone_Controls();

    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.impl.NodeImpl <em>Node</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.impl.NodeImpl
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getNode()
     * @generated
     */
    EClass NODE = eINSTANCE.getNode();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__NAME = eINSTANCE.getNode_Name();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__REF = eINSTANCE.getNode_Ref();

    /**
     * The meta object literal for the '<em><b>Host</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__HOST = eINSTANCE.getNode_Host();

    /**
     * The meta object literal for the '<em><b>Os</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__OS = eINSTANCE.getNode_Os();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE__VALUE = eINSTANCE.getNode_Value();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__COMPONENTS = eINSTANCE.getNode_Components();

    /**
     * The meta object literal for the '<em><b>Controls</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__CONTROLS = eINSTANCE.getNode_Controls();

    /**
     * The meta object literal for the '<em><b>Assets</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NODE__ASSETS = eINSTANCE.getNode_Assets();

    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.impl.ComponentImpl
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__NAME = eINSTANCE.getComponent_Name();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__REF = eINSTANCE.getComponent_Ref();

    /**
     * The meta object literal for the '<em><b>Stereotype</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__STEREOTYPE = eINSTANCE.getComponent_Stereotype();

    /**
     * The meta object literal for the '<em><b>Vendor</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__VENDOR = eINSTANCE.getComponent_Vendor();

    /**
     * The meta object literal for the '<em><b>Desc</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__DESC = eINSTANCE.getComponent_Desc();

    /**
     * The meta object literal for the '<em><b>Version</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__VERSION = eINSTANCE.getComponent_Version();

    /**
     * The meta object literal for the '<em><b>Assets</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__ASSETS = eINSTANCE.getComponent_Assets();

    /**
     * The meta object literal for the '<em><b>Controls</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__CONTROLS = eINSTANCE.getComponent_Controls();

    /**
     * The meta object literal for the '<em><b>Components</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT__COMPONENTS = eINSTANCE.getComponent_Components();

    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.impl.InformationAssetImpl <em>Information Asset</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.impl.InformationAssetImpl
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getInformationAsset()
     * @generated
     */
    EClass INFORMATION_ASSET = eINSTANCE.getInformationAsset();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INFORMATION_ASSET__NAME = eINSTANCE.getInformationAsset_Name();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INFORMATION_ASSET__REF = eINSTANCE.getInformationAsset_Ref();

    /**
     * The meta object literal for the '<em><b>Desc</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INFORMATION_ASSET__DESC = eINSTANCE.getInformationAsset_Desc();

    /**
     * The meta object literal for the '<em><b>Confidentiality</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INFORMATION_ASSET__CONFIDENTIALITY = eINSTANCE.getInformationAsset_Confidentiality();

    /**
     * The meta object literal for the '<em><b>Integrity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INFORMATION_ASSET__INTEGRITY = eINSTANCE.getInformationAsset_Integrity();

    /**
     * The meta object literal for the '<em><b>Availability</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INFORMATION_ASSET__AVAILABILITY = eINSTANCE.getInformationAsset_Availability();

    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.impl.FlowImpl <em>Flow</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.impl.FlowImpl
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getFlow()
     * @generated
     */
    EClass FLOW = eINSTANCE.getFlow();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FLOW__NAME = eINSTANCE.getFlow_Name();

    /**
     * The meta object literal for the '<em><b>From</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOW__FROM = eINSTANCE.getFlow_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOW__TO = eINSTANCE.getFlow_To();

    /**
     * The meta object literal for the '<em><b>Assets</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOW__ASSETS = eINSTANCE.getFlow_Assets();

    /**
     * The meta object literal for the '<em><b>Controls</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FLOW__CONTROLS = eINSTANCE.getFlow_Controls();

    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.impl.ControlImpl <em>Control</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.impl.ControlImpl
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getControl()
     * @generated
     */
    EClass CONTROL = eINSTANCE.getControl();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTROL__NAME = eINSTANCE.getControl_Name();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTROL__REF = eINSTANCE.getControl_Ref();

    /**
     * The meta object literal for the '<em><b>Area</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTROL__AREA = eINSTANCE.getControl_Area();

    /**
     * The meta object literal for the '<em><b>Implementation</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTROL__IMPLEMENTATION = eINSTANCE.getControl_Implementation();

    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.impl.ActorImpl <em>Actor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.impl.ActorImpl
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getActor()
     * @generated
     */
    EClass ACTOR = eINSTANCE.getActor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR__NAME = eINSTANCE.getActor_Name();

    /**
     * The meta object literal for the '<em><b>Desc</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR__DESC = eINSTANCE.getActor_Desc();

    /**
     * The meta object literal for the '<em><b>Roles</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTOR__ROLES = eINSTANCE.getActor_Roles();

    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.impl.AbstractElementImpl
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.impl.FlowEndpointImpl <em>Flow Endpoint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.impl.FlowEndpointImpl
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getFlowEndpoint()
     * @generated
     */
    EClass FLOW_ENDPOINT = eINSTANCE.getFlowEndpoint();

    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.NodeType <em>Node Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.NodeType
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getNodeType()
     * @generated
     */
    EEnum NODE_TYPE = eINSTANCE.getNodeType();

    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.ControlType <em>Control Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.ControlType
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getControlType()
     * @generated
     */
    EEnum CONTROL_TYPE = eINSTANCE.getControlType();

    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.ConfidentialityType <em>Confidentiality Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.ConfidentialityType
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getConfidentialityType()
     * @generated
     */
    EEnum CONFIDENTIALITY_TYPE = eINSTANCE.getConfidentialityType();

    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.IntegrityType <em>Integrity Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.IntegrityType
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getIntegrityType()
     * @generated
     */
    EEnum INTEGRITY_TYPE = eINSTANCE.getIntegrityType();

    /**
     * The meta object literal for the '{@link org.sabsa.dasl.dasl.AvailabilityType <em>Availability Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.sabsa.dasl.dasl.AvailabilityType
     * @see org.sabsa.dasl.dasl.impl.DaslPackageImpl#getAvailabilityType()
     * @generated
     */
    EEnum AVAILABILITY_TYPE = eINSTANCE.getAvailabilityType();

  }

} //DaslPackage
