/**
 * generated by Xtext 2.12.0
 */
package org.sabsa.dasl.dasl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Flow Endpoint</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.sabsa.dasl.dasl.DaslPackage#getFlowEndpoint()
 * @model
 * @generated
 */
public interface FlowEndpoint extends EObject
{
} // FlowEndpoint
