/**
 * generated by Xtext 2.12.0
 */
package org.sabsa.dasl.dasl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Flow</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sabsa.dasl.dasl.Flow#getName <em>Name</em>}</li>
 *   <li>{@link org.sabsa.dasl.dasl.Flow#getFrom <em>From</em>}</li>
 *   <li>{@link org.sabsa.dasl.dasl.Flow#getTo <em>To</em>}</li>
 *   <li>{@link org.sabsa.dasl.dasl.Flow#getAssets <em>Assets</em>}</li>
 *   <li>{@link org.sabsa.dasl.dasl.Flow#getControls <em>Controls</em>}</li>
 * </ul>
 *
 * @see org.sabsa.dasl.dasl.DaslPackage#getFlow()
 * @model
 * @generated
 */
public interface Flow extends AbstractElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.sabsa.dasl.dasl.DaslPackage#getFlow_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.sabsa.dasl.dasl.Flow#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>From</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>From</em>' reference.
   * @see #setFrom(Component)
   * @see org.sabsa.dasl.dasl.DaslPackage#getFlow_From()
   * @model
   * @generated
   */
  Component getFrom();

  /**
   * Sets the value of the '{@link org.sabsa.dasl.dasl.Flow#getFrom <em>From</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>From</em>' reference.
   * @see #getFrom()
   * @generated
   */
  void setFrom(Component value);

  /**
   * Returns the value of the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To</em>' reference.
   * @see #setTo(Component)
   * @see org.sabsa.dasl.dasl.DaslPackage#getFlow_To()
   * @model
   * @generated
   */
  Component getTo();

  /**
   * Sets the value of the '{@link org.sabsa.dasl.dasl.Flow#getTo <em>To</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To</em>' reference.
   * @see #getTo()
   * @generated
   */
  void setTo(Component value);

  /**
   * Returns the value of the '<em><b>Assets</b></em>' reference list.
   * The list contents are of type {@link org.sabsa.dasl.dasl.InformationAsset}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Assets</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assets</em>' reference list.
   * @see org.sabsa.dasl.dasl.DaslPackage#getFlow_Assets()
   * @model
   * @generated
   */
  EList<InformationAsset> getAssets();

  /**
   * Returns the value of the '<em><b>Controls</b></em>' reference list.
   * The list contents are of type {@link org.sabsa.dasl.dasl.Control}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Controls</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Controls</em>' reference list.
   * @see org.sabsa.dasl.dasl.DaslPackage#getFlow_Controls()
   * @model
   * @generated
   */
  EList<Control> getControls();

} // Flow
