/**
 * generated by Xtext 2.12.0
 */
package org.sabsa.dasl.dasl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Integrity Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.sabsa.dasl.dasl.DaslPackage#getIntegrityType()
 * @model
 * @generated
 */
public enum IntegrityType implements Enumerator
{
  /**
   * The '<em><b>Accurate</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACCURATE_VALUE
   * @generated
   * @ordered
   */
  ACCURATE(0, "Accurate", "Accurate"),

  /**
   * The '<em><b>Highly Trusted</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #HIGHLY_TRUSTED_VALUE
   * @generated
   * @ordered
   */
  HIGHLY_TRUSTED(1, "HighlyTrusted", "HighlyTrusted"),

  /**
   * The '<em><b>Trusted</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #TRUSTED_VALUE
   * @generated
   * @ordered
   */
  TRUSTED(2, "Trusted", "Trusted"),

  /**
   * The '<em><b>Uncontrolled</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UNCONTROLLED_VALUE
   * @generated
   * @ordered
   */
  UNCONTROLLED(3, "Uncontrolled", "Uncontrolled");

  /**
   * The '<em><b>Accurate</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Accurate</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #ACCURATE
   * @model name="Accurate"
   * @generated
   * @ordered
   */
  public static final int ACCURATE_VALUE = 0;

  /**
   * The '<em><b>Highly Trusted</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Highly Trusted</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #HIGHLY_TRUSTED
   * @model name="HighlyTrusted"
   * @generated
   * @ordered
   */
  public static final int HIGHLY_TRUSTED_VALUE = 1;

  /**
   * The '<em><b>Trusted</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Trusted</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #TRUSTED
   * @model name="Trusted"
   * @generated
   * @ordered
   */
  public static final int TRUSTED_VALUE = 2;

  /**
   * The '<em><b>Uncontrolled</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of '<em><b>Uncontrolled</b></em>' literal object isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @see #UNCONTROLLED
   * @model name="Uncontrolled"
   * @generated
   * @ordered
   */
  public static final int UNCONTROLLED_VALUE = 3;

  /**
   * An array of all the '<em><b>Integrity Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final IntegrityType[] VALUES_ARRAY =
    new IntegrityType[]
    {
      ACCURATE,
      HIGHLY_TRUSTED,
      TRUSTED,
      UNCONTROLLED,
    };

  /**
   * A public read-only list of all the '<em><b>Integrity Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<IntegrityType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Integrity Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static IntegrityType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      IntegrityType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Integrity Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static IntegrityType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      IntegrityType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Integrity Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static IntegrityType get(int value)
  {
    switch (value)
    {
      case ACCURATE_VALUE: return ACCURATE;
      case HIGHLY_TRUSTED_VALUE: return HIGHLY_TRUSTED;
      case TRUSTED_VALUE: return TRUSTED;
      case UNCONTROLLED_VALUE: return UNCONTROLLED;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private IntegrityType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //IntegrityType
