/**
 * generated by Xtext 2.19.0
 */
package org.sabsa.dasl.dasl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Metadata</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sabsa.dasl.dasl.Metadata#getKeys <em>Keys</em>}</li>
 * </ul>
 *
 * @see org.sabsa.dasl.dasl.DaslPackage#getMetadata()
 * @model
 * @generated
 */
public interface Metadata extends EObject
{
  /**
   * Returns the value of the '<em><b>Keys</b></em>' attribute list.
   * The list contents are of type {@link org.sabsa.dasl.dasl.MetadataType}.
   * The literals are from the enumeration {@link org.sabsa.dasl.dasl.MetadataType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keys</em>' attribute list.
   * @see org.sabsa.dasl.dasl.MetadataType
   * @see org.sabsa.dasl.dasl.DaslPackage#getMetadata_Keys()
   * @model unique="false"
   * @generated
   */
  EList<MetadataType> getKeys();

} // Metadata
