/**
 * generated by Xtext 2.19.0
 */
package org.sabsa.dasl.dasl;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>NIST80053A Rev4 Family Type</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.sabsa.dasl.dasl.DaslPackage#getNIST80053ARev4_FamilyType()
 * @model
 * @generated
 */
public enum NIST80053ARev4_FamilyType implements Enumerator
{
  /**
   * The '<em><b>ACCESS CONTROL</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACCESS_CONTROL_VALUE
   * @generated
   * @ordered
   */
  ACCESS_CONTROL(0, "ACCESS_CONTROL", "ACCESS_CONTROL"),

  /**
   * The '<em><b>AWARENESS AND TRAINING</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AWARENESS_AND_TRAINING_VALUE
   * @generated
   * @ordered
   */
  AWARENESS_AND_TRAINING(1, "AWARENESS_AND_TRAINING", "AWARENESS_AND_TRAINING"),

  /**
   * The '<em><b>AUDIT AND ACCOUNTABILITY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AUDIT_AND_ACCOUNTABILITY_VALUE
   * @generated
   * @ordered
   */
  AUDIT_AND_ACCOUNTABILITY(2, "AUDIT_AND_ACCOUNTABILITY", "AUDIT_AND_ACCOUNTABILITY"),

  /**
   * The '<em><b>SECURITY ASSESSMENT AND AUTHORIZATION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SECURITY_ASSESSMENT_AND_AUTHORIZATION_VALUE
   * @generated
   * @ordered
   */
  SECURITY_ASSESSMENT_AND_AUTHORIZATION(3, "SECURITY_ASSESSMENT_AND_AUTHORIZATION", "SECURITY_ASSESSMENT_AND_AUTHORIZATION"),

  /**
   * The '<em><b>CONFIGURATION MANAGEMENT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CONFIGURATION_MANAGEMENT_VALUE
   * @generated
   * @ordered
   */
  CONFIGURATION_MANAGEMENT(4, "CONFIGURATION_MANAGEMENT", "CONFIGURATION_MANAGEMENT"),

  /**
   * The '<em><b>CONTINGENCY PLANNING</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CONTINGENCY_PLANNING_VALUE
   * @generated
   * @ordered
   */
  CONTINGENCY_PLANNING(5, "CONTINGENCY_PLANNING", "CONTINGENCY_PLANNING"),

  /**
   * The '<em><b>IDENTIFICATION AND AUTHENTICATION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IDENTIFICATION_AND_AUTHENTICATION_VALUE
   * @generated
   * @ordered
   */
  IDENTIFICATION_AND_AUTHENTICATION(6, "IDENTIFICATION_AND_AUTHENTICATION", "IDENTIFICATION_AND_AUTHENTICATION"),

  /**
   * The '<em><b>INCIDENT RESPONSE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INCIDENT_RESPONSE_VALUE
   * @generated
   * @ordered
   */
  INCIDENT_RESPONSE(7, "INCIDENT_RESPONSE", "INCIDENT_RESPONSE"),

  /**
   * The '<em><b>MAINTENANCE</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MAINTENANCE_VALUE
   * @generated
   * @ordered
   */
  MAINTENANCE(8, "MAINTENANCE", "MAINTENANCE"),

  /**
   * The '<em><b>MEDIA PROTECTION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MEDIA_PROTECTION_VALUE
   * @generated
   * @ordered
   */
  MEDIA_PROTECTION(9, "MEDIA_PROTECTION", "MEDIA_PROTECTION"),

  /**
   * The '<em><b>PHYSICAL AND ENVIRONMENTAL PROTECTION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PHYSICAL_AND_ENVIRONMENTAL_PROTECTION_VALUE
   * @generated
   * @ordered
   */
  PHYSICAL_AND_ENVIRONMENTAL_PROTECTION(10, "PHYSICAL_AND_ENVIRONMENTAL_PROTECTION", "PHYSICAL_AND_ENVIRONMENTAL_PROTECTION"),

  /**
   * The '<em><b>PLANNING</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PLANNING_VALUE
   * @generated
   * @ordered
   */
  PLANNING(11, "PLANNING", "PLANNING"),

  /**
   * The '<em><b>PROGRAM MANAGEMENT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PROGRAM_MANAGEMENT_VALUE
   * @generated
   * @ordered
   */
  PROGRAM_MANAGEMENT(12, "PROGRAM_MANAGEMENT", "PROGRAM_MANAGEMENT"),

  /**
   * The '<em><b>PERSONNEL SECURITY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PERSONNEL_SECURITY_VALUE
   * @generated
   * @ordered
   */
  PERSONNEL_SECURITY(13, "PERSONNEL_SECURITY", "PERSONNEL_SECURITY"),

  /**
   * The '<em><b>RISK ASSESSMENT</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RISK_ASSESSMENT_VALUE
   * @generated
   * @ordered
   */
  RISK_ASSESSMENT(14, "RISK_ASSESSMENT", "RISK_ASSESSMENT"),

  /**
   * The '<em><b>SYSTEM AND SERVICES ACQUISITION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SYSTEM_AND_SERVICES_ACQUISITION_VALUE
   * @generated
   * @ordered
   */
  SYSTEM_AND_SERVICES_ACQUISITION(15, "SYSTEM_AND_SERVICES_ACQUISITION", "SYSTEM_AND_SERVICES_ACQUISITION"),

  /**
   * The '<em><b>SYSTEM AND COMMUNICATIONS PROTECTION</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SYSTEM_AND_COMMUNICATIONS_PROTECTION_VALUE
   * @generated
   * @ordered
   */
  SYSTEM_AND_COMMUNICATIONS_PROTECTION(16, "SYSTEM_AND_COMMUNICATIONS_PROTECTION", "SYSTEM_AND_COMMUNICATIONS_PROTECTION"),

  /**
   * The '<em><b>SYSTEM AND INFORMATION INTEGRITY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SYSTEM_AND_INFORMATION_INTEGRITY_VALUE
   * @generated
   * @ordered
   */
  SYSTEM_AND_INFORMATION_INTEGRITY(17, "SYSTEM_AND_INFORMATION_INTEGRITY", "SYSTEM_AND_INFORMATION_INTEGRITY");

  /**
   * The '<em><b>ACCESS CONTROL</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ACCESS_CONTROL
   * @model
   * @generated
   * @ordered
   */
  public static final int ACCESS_CONTROL_VALUE = 0;

  /**
   * The '<em><b>AWARENESS AND TRAINING</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AWARENESS_AND_TRAINING
   * @model
   * @generated
   * @ordered
   */
  public static final int AWARENESS_AND_TRAINING_VALUE = 1;

  /**
   * The '<em><b>AUDIT AND ACCOUNTABILITY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AUDIT_AND_ACCOUNTABILITY
   * @model
   * @generated
   * @ordered
   */
  public static final int AUDIT_AND_ACCOUNTABILITY_VALUE = 2;

  /**
   * The '<em><b>SECURITY ASSESSMENT AND AUTHORIZATION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SECURITY_ASSESSMENT_AND_AUTHORIZATION
   * @model
   * @generated
   * @ordered
   */
  public static final int SECURITY_ASSESSMENT_AND_AUTHORIZATION_VALUE = 3;

  /**
   * The '<em><b>CONFIGURATION MANAGEMENT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CONFIGURATION_MANAGEMENT
   * @model
   * @generated
   * @ordered
   */
  public static final int CONFIGURATION_MANAGEMENT_VALUE = 4;

  /**
   * The '<em><b>CONTINGENCY PLANNING</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CONTINGENCY_PLANNING
   * @model
   * @generated
   * @ordered
   */
  public static final int CONTINGENCY_PLANNING_VALUE = 5;

  /**
   * The '<em><b>IDENTIFICATION AND AUTHENTICATION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IDENTIFICATION_AND_AUTHENTICATION
   * @model
   * @generated
   * @ordered
   */
  public static final int IDENTIFICATION_AND_AUTHENTICATION_VALUE = 6;

  /**
   * The '<em><b>INCIDENT RESPONSE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #INCIDENT_RESPONSE
   * @model
   * @generated
   * @ordered
   */
  public static final int INCIDENT_RESPONSE_VALUE = 7;

  /**
   * The '<em><b>MAINTENANCE</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MAINTENANCE
   * @model
   * @generated
   * @ordered
   */
  public static final int MAINTENANCE_VALUE = 8;

  /**
   * The '<em><b>MEDIA PROTECTION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MEDIA_PROTECTION
   * @model
   * @generated
   * @ordered
   */
  public static final int MEDIA_PROTECTION_VALUE = 9;

  /**
   * The '<em><b>PHYSICAL AND ENVIRONMENTAL PROTECTION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PHYSICAL_AND_ENVIRONMENTAL_PROTECTION
   * @model
   * @generated
   * @ordered
   */
  public static final int PHYSICAL_AND_ENVIRONMENTAL_PROTECTION_VALUE = 10;

  /**
   * The '<em><b>PLANNING</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PLANNING
   * @model
   * @generated
   * @ordered
   */
  public static final int PLANNING_VALUE = 11;

  /**
   * The '<em><b>PROGRAM MANAGEMENT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PROGRAM_MANAGEMENT
   * @model
   * @generated
   * @ordered
   */
  public static final int PROGRAM_MANAGEMENT_VALUE = 12;

  /**
   * The '<em><b>PERSONNEL SECURITY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PERSONNEL_SECURITY
   * @model
   * @generated
   * @ordered
   */
  public static final int PERSONNEL_SECURITY_VALUE = 13;

  /**
   * The '<em><b>RISK ASSESSMENT</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RISK_ASSESSMENT
   * @model
   * @generated
   * @ordered
   */
  public static final int RISK_ASSESSMENT_VALUE = 14;

  /**
   * The '<em><b>SYSTEM AND SERVICES ACQUISITION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SYSTEM_AND_SERVICES_ACQUISITION
   * @model
   * @generated
   * @ordered
   */
  public static final int SYSTEM_AND_SERVICES_ACQUISITION_VALUE = 15;

  /**
   * The '<em><b>SYSTEM AND COMMUNICATIONS PROTECTION</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SYSTEM_AND_COMMUNICATIONS_PROTECTION
   * @model
   * @generated
   * @ordered
   */
  public static final int SYSTEM_AND_COMMUNICATIONS_PROTECTION_VALUE = 16;

  /**
   * The '<em><b>SYSTEM AND INFORMATION INTEGRITY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SYSTEM_AND_INFORMATION_INTEGRITY
   * @model
   * @generated
   * @ordered
   */
  public static final int SYSTEM_AND_INFORMATION_INTEGRITY_VALUE = 17;

  /**
   * An array of all the '<em><b>NIST80053A Rev4 Family Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final NIST80053ARev4_FamilyType[] VALUES_ARRAY =
    new NIST80053ARev4_FamilyType[]
    {
      ACCESS_CONTROL,
      AWARENESS_AND_TRAINING,
      AUDIT_AND_ACCOUNTABILITY,
      SECURITY_ASSESSMENT_AND_AUTHORIZATION,
      CONFIGURATION_MANAGEMENT,
      CONTINGENCY_PLANNING,
      IDENTIFICATION_AND_AUTHENTICATION,
      INCIDENT_RESPONSE,
      MAINTENANCE,
      MEDIA_PROTECTION,
      PHYSICAL_AND_ENVIRONMENTAL_PROTECTION,
      PLANNING,
      PROGRAM_MANAGEMENT,
      PERSONNEL_SECURITY,
      RISK_ASSESSMENT,
      SYSTEM_AND_SERVICES_ACQUISITION,
      SYSTEM_AND_COMMUNICATIONS_PROTECTION,
      SYSTEM_AND_INFORMATION_INTEGRITY,
    };

  /**
   * A public read-only list of all the '<em><b>NIST80053A Rev4 Family Type</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<NIST80053ARev4_FamilyType> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>NIST80053A Rev4 Family Type</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static NIST80053ARev4_FamilyType get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      NIST80053ARev4_FamilyType result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>NIST80053A Rev4 Family Type</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static NIST80053ARev4_FamilyType getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      NIST80053ARev4_FamilyType result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>NIST80053A Rev4 Family Type</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static NIST80053ARev4_FamilyType get(int value)
  {
    switch (value)
    {
      case ACCESS_CONTROL_VALUE: return ACCESS_CONTROL;
      case AWARENESS_AND_TRAINING_VALUE: return AWARENESS_AND_TRAINING;
      case AUDIT_AND_ACCOUNTABILITY_VALUE: return AUDIT_AND_ACCOUNTABILITY;
      case SECURITY_ASSESSMENT_AND_AUTHORIZATION_VALUE: return SECURITY_ASSESSMENT_AND_AUTHORIZATION;
      case CONFIGURATION_MANAGEMENT_VALUE: return CONFIGURATION_MANAGEMENT;
      case CONTINGENCY_PLANNING_VALUE: return CONTINGENCY_PLANNING;
      case IDENTIFICATION_AND_AUTHENTICATION_VALUE: return IDENTIFICATION_AND_AUTHENTICATION;
      case INCIDENT_RESPONSE_VALUE: return INCIDENT_RESPONSE;
      case MAINTENANCE_VALUE: return MAINTENANCE;
      case MEDIA_PROTECTION_VALUE: return MEDIA_PROTECTION;
      case PHYSICAL_AND_ENVIRONMENTAL_PROTECTION_VALUE: return PHYSICAL_AND_ENVIRONMENTAL_PROTECTION;
      case PLANNING_VALUE: return PLANNING;
      case PROGRAM_MANAGEMENT_VALUE: return PROGRAM_MANAGEMENT;
      case PERSONNEL_SECURITY_VALUE: return PERSONNEL_SECURITY;
      case RISK_ASSESSMENT_VALUE: return RISK_ASSESSMENT;
      case SYSTEM_AND_SERVICES_ACQUISITION_VALUE: return SYSTEM_AND_SERVICES_ACQUISITION;
      case SYSTEM_AND_COMMUNICATIONS_PROTECTION_VALUE: return SYSTEM_AND_COMMUNICATIONS_PROTECTION;
      case SYSTEM_AND_INFORMATION_INTEGRITY_VALUE: return SYSTEM_AND_INFORMATION_INTEGRITY;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private NIST80053ARev4_FamilyType(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //NIST80053ARev4_FamilyType
