/*
 * generated by Xtext 2.12.0
 */
package org.sabsa.dasl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDaslScopeProvider extends DelegatingScopeProvider {
}
