/*
 * generated by Xtext 2.12.0
 */
package org.sabsa.dasl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.sabsa.dasl.DaslRuntimeModule
import org.sabsa.dasl.DaslStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class DaslIdeSetup extends DaslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new DaslRuntimeModule, new DaslIdeModule))
	}
	
}
